"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
// This file was autogenerated by `create-eas-build-function` command.
// Go to README.md to learn more about how to write your own custom build functions.

function myFunction(ctx, {
  inputs,
  outputs,
  env
}) {
  ctx.logger.info('Hello from my JavaScript function!');
}
var _default = myFunction;
exports.default = _default;